# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alex/Documents/New-Simu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alex/Documents/New-Simu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/Documents/New-Simu/CMakeFiles /home/alex/Documents/New-Simu/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/Documents/New-Simu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named New-simu

# Build rule for target.
New-simu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 New-simu
.PHONY : New-simu

# fast build rule for target.
New-simu/fast:
	$(MAKE) -f CMakeFiles/New-simu.dir/build.make CMakeFiles/New-simu.dir/build
.PHONY : New-simu/fast

src/equipo.o: src/equipo.cpp.o

.PHONY : src/equipo.o

# target to build an object file
src/equipo.cpp.o:
	$(MAKE) -f CMakeFiles/New-simu.dir/build.make CMakeFiles/New-simu.dir/src/equipo.cpp.o
.PHONY : src/equipo.cpp.o

src/equipo.i: src/equipo.cpp.i

.PHONY : src/equipo.i

# target to preprocess a source file
src/equipo.cpp.i:
	$(MAKE) -f CMakeFiles/New-simu.dir/build.make CMakeFiles/New-simu.dir/src/equipo.cpp.i
.PHONY : src/equipo.cpp.i

src/equipo.s: src/equipo.cpp.s

.PHONY : src/equipo.s

# target to generate assembly for a file
src/equipo.cpp.s:
	$(MAKE) -f CMakeFiles/New-simu.dir/build.make CMakeFiles/New-simu.dir/src/equipo.cpp.s
.PHONY : src/equipo.cpp.s

src/jugador.o: src/jugador.cpp.o

.PHONY : src/jugador.o

# target to build an object file
src/jugador.cpp.o:
	$(MAKE) -f CMakeFiles/New-simu.dir/build.make CMakeFiles/New-simu.dir/src/jugador.cpp.o
.PHONY : src/jugador.cpp.o

src/jugador.i: src/jugador.cpp.i

.PHONY : src/jugador.i

# target to preprocess a source file
src/jugador.cpp.i:
	$(MAKE) -f CMakeFiles/New-simu.dir/build.make CMakeFiles/New-simu.dir/src/jugador.cpp.i
.PHONY : src/jugador.cpp.i

src/jugador.s: src/jugador.cpp.s

.PHONY : src/jugador.s

# target to generate assembly for a file
src/jugador.cpp.s:
	$(MAKE) -f CMakeFiles/New-simu.dir/build.make CMakeFiles/New-simu.dir/src/jugador.cpp.s
.PHONY : src/jugador.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/New-simu.dir/build.make CMakeFiles/New-simu.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/New-simu.dir/build.make CMakeFiles/New-simu.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/New-simu.dir/build.make CMakeFiles/New-simu.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/position.o: src/position.cpp.o

.PHONY : src/position.o

# target to build an object file
src/position.cpp.o:
	$(MAKE) -f CMakeFiles/New-simu.dir/build.make CMakeFiles/New-simu.dir/src/position.cpp.o
.PHONY : src/position.cpp.o

src/position.i: src/position.cpp.i

.PHONY : src/position.i

# target to preprocess a source file
src/position.cpp.i:
	$(MAKE) -f CMakeFiles/New-simu.dir/build.make CMakeFiles/New-simu.dir/src/position.cpp.i
.PHONY : src/position.cpp.i

src/position.s: src/position.cpp.s

.PHONY : src/position.s

# target to generate assembly for a file
src/position.cpp.s:
	$(MAKE) -f CMakeFiles/New-simu.dir/build.make CMakeFiles/New-simu.dir/src/position.cpp.s
.PHONY : src/position.cpp.s

src/tactic.o: src/tactic.cpp.o

.PHONY : src/tactic.o

# target to build an object file
src/tactic.cpp.o:
	$(MAKE) -f CMakeFiles/New-simu.dir/build.make CMakeFiles/New-simu.dir/src/tactic.cpp.o
.PHONY : src/tactic.cpp.o

src/tactic.i: src/tactic.cpp.i

.PHONY : src/tactic.i

# target to preprocess a source file
src/tactic.cpp.i:
	$(MAKE) -f CMakeFiles/New-simu.dir/build.make CMakeFiles/New-simu.dir/src/tactic.cpp.i
.PHONY : src/tactic.cpp.i

src/tactic.s: src/tactic.cpp.s

.PHONY : src/tactic.s

# target to generate assembly for a file
src/tactic.cpp.s:
	$(MAKE) -f CMakeFiles/New-simu.dir/build.make CMakeFiles/New-simu.dir/src/tactic.cpp.s
.PHONY : src/tactic.cpp.s

src/textmisc.o: src/textmisc.cpp.o

.PHONY : src/textmisc.o

# target to build an object file
src/textmisc.cpp.o:
	$(MAKE) -f CMakeFiles/New-simu.dir/build.make CMakeFiles/New-simu.dir/src/textmisc.cpp.o
.PHONY : src/textmisc.cpp.o

src/textmisc.i: src/textmisc.cpp.i

.PHONY : src/textmisc.i

# target to preprocess a source file
src/textmisc.cpp.i:
	$(MAKE) -f CMakeFiles/New-simu.dir/build.make CMakeFiles/New-simu.dir/src/textmisc.cpp.i
.PHONY : src/textmisc.cpp.i

src/textmisc.s: src/textmisc.cpp.s

.PHONY : src/textmisc.s

# target to generate assembly for a file
src/textmisc.cpp.s:
	$(MAKE) -f CMakeFiles/New-simu.dir/build.make CMakeFiles/New-simu.dir/src/textmisc.cpp.s
.PHONY : src/textmisc.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... New-simu"
	@echo "... src/equipo.o"
	@echo "... src/equipo.i"
	@echo "... src/equipo.s"
	@echo "... src/jugador.o"
	@echo "... src/jugador.i"
	@echo "... src/jugador.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/position.o"
	@echo "... src/position.i"
	@echo "... src/position.s"
	@echo "... src/tactic.o"
	@echo "... src/tactic.i"
	@echo "... src/tactic.s"
	@echo "... src/textmisc.o"
	@echo "... src/textmisc.i"
	@echo "... src/textmisc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

